# Generated by Django 5.2 on 2025-04-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
